InputParameters:
  FixedVolume:
    Dimension: {x: 394, y: 466, z: 378} #MUST 
    Spacing: {x: 0.5, y: 0.5, z: 0.5} #MUST 
    Origin: {x: -98.0, y: -134.0, z: -72.0} #OPTION, 0 0 0 
    FilePath: /home/wenhai/img_registration_ws/mni_group01/01_mr_tal.raw #MUST 
    Format: raw #MUST 
    DataType: float32
    Label: CT_CoronalViewFToB MNI_dataset
  MovingVolume:
    Dimension: {x: 323, y: 366, z: 371} #MUST 
    Spacing: {x: 0.3, y: 0.3, z: 0.3} #MUST 
    Origin: {x: -42.2, y: -52.7, z: -59.4} #OPTION, 0 0 0 
    FilePath: /home/wenhai/img_registration_ws/mni_group01/01a_us_tal.raw #MUST 
    Format: raw #MUST 
    DataType: float32
    Label: Ultrasound_Volume MNI_dataset
  RegistrationParameters:
    HighResolutionModality: Fixed # or Moving
    Type: Affine
    DisplayPattern: 0
    ResampledSpacing: {x: 1.3, y: 1.3, z: 1.3} #MUST, [mm] virtual space, z = max(spacing_fixed, spacing_moving, 1.3)
    PatchSize: 3 #MUST 
    FinalRoundExportRootPath: /home/wenhai/img_registration_ws/mni_group01 #MUST 
    CenterOverlaid: false 
  OptimizerSettings:
    InitialValues: {TX: 0.0, TY: 0.0, TZ: 0.0, RX: 0.0, RY: 0.0, RZ: 0.0, ScaleX: 1.0, ScaleY: 1.0, ScaleZ: 1.0, ShearX: 0.0, ShearY: 0.0, ShearZ: 0.0}  
    LowerBounds: {TX: -30.0, TY: -30.0, TZ: -30.0, RX: -15.0, RY: -15.0, RZ: -15.0, ScaleX: 0.8, ScaleY: 0.8, ScaleZ: 0.8, ShearX: -0.2, ShearY: -0.2, ShearZ: -0.2}
    UpperBounds: {TX: 30.0, TY: 30.0, TZ: 30.0, RX: 15.0, RY: 15.0, RZ: 15.0, ScaleX: 1.2, ScaleY: 1.2, ScaleZ: 1.2, ShearX: 0.2, ShearY: 0.2, ShearZ: 0.2}
    DIRECT:
      Enabled: true
      OptimizedEntries: {Translation: true, Rotation: false, Scale: false, Shear: false}
      MaxEvaluations: 50  
    BOBYQA:
      0: 
        Enabled: true
        OptimizedEntries: {Translation: true, Rotation: true, Scale: false, Shear: false}
        AbsTol: 1.0e-4
      1: 
        Enabled: true
        OptimizedEntries: {Translation: true, Rotation: true, Scale: true, Shear: true}
        AbsTol: 1.0e-4
Outputs:
  IsRegistered: true
  TransformMatrix:
    -
      - 0.999353051
      - -0.0348830447
      - -0.00875627343
      - 0.769383967
    -
      - 0.0348841809
      - 0.999391377
      - -2.28275894e-05
      - 1.72534144
    -
      - 0.00875173975
      - -0.000282642577
      - 0.999961734
      - 0.149243146
    -
      - 0
      - 0
      - 0
      - 1
  LastSimilarity: 0.151439726
  NumEvaluations: 239
  RegistrationDateTime: sd
